#pragma once
// GENERATED BY FALCON VST MAKER — no background image set
namespace falconbgfx
{
    static constexpr bool hasImage = false;
    static const unsigned char imageData[1] = { 0 };
    static constexpr int imageDataSize = 0;
}
