; Falcon Echo 2026 — Windows installer (generated by Falcon VST Maker)

#define AppName      "Falcon Echo 2026"
#define AppVersion   "1.0.0"
#define Publisher    "Falcon Eye Corporation"
#define PublisherURL "https://www.falconeyesl.com"
#define BuildDir     "K:\VST Build in Maker\FalconEcho2026\build\FalconEcho2026_artefacts\Release"

[Setup]
AppId=FalconMaker-e392d6fa3a436618
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#Publisher}
AppPublisherURL={#PublisherURL}
AppSupportURL={#PublisherURL}
DefaultDirName={autopf}\{#Publisher}\{#AppName}
DefaultGroupName={#Publisher}
DisableProgramGroupPage=yes
OutputDir=K:\VST Build in Maker\FalconEcho2026\output
OutputBaseFilename=FalconEcho2026-{#AppVersion}-Setup
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64compatible
ArchitecturesAllowed=x64compatible
UninstallDisplayIcon={app}\{#AppName}.exe
SetupIconFile={#SourcePath}\icon.ico

[Types]
Name: "full";    Description: "Full installation (VST3 + Standalone)"
Name: "vstonly"; Description: "VST3 plugin only"
Name: "custom";  Description: "Custom"; Flags: iscustom

[Components]
Name: "vst3";       Description: "{#AppName} VST3 plugin (all DAWs)"; Types: full vstonly custom; Flags: fixed
Name: "standalone"; Description: "{#AppName} Standalone application"; Types: full custom

[Files]
Source: "{#BuildDir}\VST3\{#AppName}.vst3\*"; DestDir: "{commoncf64}\VST3\{#AppName}.vst3"; \
    Components: vst3; Flags: recursesubdirs createallsubdirs ignoreversion
Source: "{#BuildDir}\Standalone\{#AppName}.exe"; DestDir: "{app}"; \
    Components: standalone; Flags: ignoreversion

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppName}.exe"; Components: standalone
Name: "{group}\Uninstall {#AppName}"; Filename: "{uninstallexe}"

[Run]
Filename: "{app}\{#AppName}.exe"; Description: "Launch {#AppName}"; \
    Components: standalone; Flags: nowait postinstall skipifsilent runasoriginaluser

[UninstallDelete]
Type: dirifempty; Name: "{commoncf64}\VST3\{#AppName}.vst3"
